### ISSUE TITLE
The plugin is not working as described 

### ISSUE THREAD

**Issue by nebtunes** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#15] opened 2018-01-23 15:43 UTC
Hello, I just installed the plugin but its not working as described. Its redirects to payment page, its dosen't show model box. Also, after it redirects to payment page, It dosen't send back any response to the online store.

I will be happy if there's a way you can fix it.
Thanks.

**Comment by bosunolanrewaju** [comment] 2018-01-24 10:23
@nebtunes Thank you for reporting. Please what version of WooCommerce and WordPress are you using?

**Comment by nebtunes** [comment] 2018-01-24 10:25
@bosunolanrewaju Am using WordPress Version 4.9.2 and WooCommerce Version: 3.2.6

**Comment by bosunolanrewaju** [comment] 2018-01-24 10:30
So if I get the issue clearly, it is that when a user clicks the "PAY NOW" button nothing happens or what? I need to know what happens when the button is clicked to be able to debug. If the website is live, you can also share the URL so I can have a quick look.

**Comment by nebtunes** [comment] 2018-01-24 10:39
Here is the website website: http://www.flawlessbeautybymimi.com. check and see. am still working on it though.

**Comment by nebtunes** [comment] 2018-01-25 18:11
Hello, Have you fixed the issue please?

**Comment by bosunolanrewaju** [comment] 2018-01-26 10:13
@nebtunes Sorry for the delay in responding. Unfortunately, I can't access the checkout page on the website you shared. If we have to get to the bottom of this, I will have to have access to the website's checkout page. 

Let me know when I can access the checkout page.

**Comment by nebtunes** [comment] 2018-01-26 12:22
@bosunolanrewaju what's your email so that I can send you the credentials to the website so that you can fix it. Thanks

**Comment by bosunolanrewaju** [comment] 2018-01-26 13:09
@nebtunes Here: kiyireb@69postix.info

**Comment by bosunolanrewaju** [comment] 2018-01-26 14:32
@nebtunes I tested the plugin on the checkout page and I was successfully redirected to Ravepay's page to enter my card information. I don't see any issue here because the plugin is working as it should.

**Comment by nebtunes** [comment] 2018-01-26 15:17
Yes but that is test. Also, it is supposed to be a modal box not redirect to rave pay. If I switch to live and pay. After it redirects to payment page, It doesn't send back any response to the online store. on live. That's the issue.

**Comment by bosunolanrewaju** [comment] 2018-01-26 15:28
You should talk to the Rave support. I don't think that is caused by the plugin

**Comment by nebtunes** [comment] 2018-01-26 15:43
OK, let me talk to them and get back to you then.
Thanks

**Comment by bosunolanrewaju** [comment] 2018-03-16 11:40
@nebtunes I am closing this issue as what was reported is not caused by the plugin. If you think otherwise, feel free to re-open it

**Closed as completed by bosunolanrewaju** 2018-03-16 11:40 UTC
