### ISSUE TITLE
jQuery pop-up issues

### ISSUE THREAD

**Issue by afeletov** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#6] opened 2017-05-08 08:03 UTC
Hello, Thanks for the effort in making this plugin great. I recently experienced an issue which I wanted to bring to your attention. The "Pay Now" button doesn't seem to work on some browsers..most noticeably in mobile versions of chrome. Please, would this be an issue with WordPress or the plugin.
URL: www.sirernest2020projects.com/shop

**Comment by bosunolanrewaju** [comment] 2017-05-08 15:23
@afeletov I'm sorry to hear about the issue you experienced using this plugin. I tried to access the link you provided, but it is not going through. Please confirm that the url is correct.

**Comment by afeletov** [comment] 2017-05-08 15:33
Please find below the correct URL 
www.sirernest2020projects.com/shop

**Comment by bosunolanrewaju** [comment] 2017-05-08 18:10
@afeletov I have tested the plugin on both desktop and mobile chrome browser and they both worked. You should check that JavaScript is enabled on the mobile browser as it is required for the plugin to work.
![See Image](https://cloud.githubusercontent.com/assets/8383666/25818259/f4d6ba36-3421-11e7-9e12-c3bf784ab72d.jpeg)

**Comment by bosunolanrewaju** [comment] 2017-05-15 23:44
@afeletov It 1 week since my last reply. I am closing this issue. Feel free to open if you still have the issue after you have confirmed that JavaScript is enabled.

**Closed as completed by bosunolanrewaju** 2017-05-15 23:44 UTC
